// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Untitled', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Untitled', async function() {
    // Test name: Untitled
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("https://www.rottentomatoes.com/")
    // 2 | setWindowSize | 1099x875 | 
    await driver.manage().window().setRect(1099, 875)
    // 3 | mouseOver | id=nav-search-submit-button | 
    {
      const element = await driver.findElement(By.id("nav-search-submit-button"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 4 | click | id=twotabsearchtextbox | 
    await driver.findElement(By.id("twotabsearchtextbox")).click()
    // 5 | type | id=twotabsearchtextbox | playstation 4 console
    await driver.findElement(By.id("twotabsearchtextbox")).sendKeys("playstation 4 console")
    // 6 | sendKeys | id=twotabsearchtextbox | ${KEY_ENTER}
    await driver.findElement(By.id("twotabsearchtextbox")).sendKeys(Key.ENTER)
  })
})
