// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('test2', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('test2', async function() {
    // Test name: test2
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("https://www.google.es/")
    // 2 | setWindowSize | 858x855 | 
    //await driver.manage().window().setRect(858, 855)

    
    try{
      // 3 | selectFrame | index=0 | 
      await driver.switchTo().frame(0)
      // 4 | click | css=#introAgreeButton .RveJvd | 
      await driver.wait(until.elementLocated(By.css("#introAgreeButton .RveJvd"))).click();
      // 5 | selectFrame | relative=parent | 
      await driver.switchTo().defaultContent()
    }catch{
      console.log("no hay popup");
    }
    
    // 6 | click | name=q | 
    await driver.findElement(By.name("q")).click()
    // 7 | type | name=q | devops
    await driver.findElement(By.name("q")).sendKeys("devops")
    // 8 | sendKeys | name=q | ${KEY_ENTER}
    await driver.findElement(By.name("q")).sendKeys(Key.ENTER)
    // 9 | click | xpath=//div[@id='tads']/div/div/div/div/a/div | 
    await driver.wait(until.elementLocated(By.xpath("//div[@id=\'tads\']/div/div/div/div/a/div"))).click()
  })
})
