// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('test-google', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('test-google', async function() {
    // Test name: test-google
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("https://www.google.es/")
    // 2 | setWindowSize | 858x852 | 
    await driver.manage().window().setRect(858, 852)
    // 3 | selectFrame | index=0 | 
    await driver.switchTo().frame(0)
    // 4 | click | css=#introAgreeButton .RveJvd | 
    await driver.findElement(By.css("#introAgreeButton .RveJvd")).click()
    // 5 | selectFrame | relative=parent | 
    await driver.switchTo().defaultContent()
    // 6 | click | name=q | 
    await driver.findElement(By.name("q")).click()
    // 7 | type | name=q | devops
    await driver.findElement(By.name("q")).sendKeys("devops")
    // 8 | sendKeys | name=q | ${KEY_ENTER}
    await driver.findElement(By.name("q")).sendKeys(Key.ENTER)
    // 9 | mouseOver | css=.cfxYMc | 
    {
      const element = await driver.findElement(By.css(".cfxYMc"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 10 | click | css=.cfxYMc | 
    await driver.findElement(By.css(".cfxYMc")).click()
    // 11 | mouseOut | css=.cfxYMc | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
  })
})
