// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SabernombresinputnumerTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void sabernombresinputnumer() {
    // Test name: saber nombres input numer
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://localhost:3000/");
    // 2 | setWindowSize | 858x860 | 
    driver.manage().window().setSize(new Dimension(858, 860));
    // 3 | click | css=.ng-scope:nth-child(1) > td .form-control | 
    driver.findElement(By.cssSelector(".ng-scope:nth-child(1) > td .form-control")).click();
    // 4 | click | css=.ng-scope:nth-child(2) > td .form-control | 
    driver.findElement(By.cssSelector(".ng-scope:nth-child(2) > td .form-control")).click();
    // 5 | click | css=.ng-untouched | 
    driver.findElement(By.cssSelector(".ng-untouched")).click();
  }
}
