#!/usr/bin/env node
// Generated by Selenium

const {Builder, By, Key, until, Capabilities, Browser} = require('selenium-webdriver')
const assert = require('assert')

async('SeleniumGridRobobar', function () {
    this.timeout(30000)
    let driver
    let vars
    let capabilities = new Capabilities().setBrowserName("chrome");
    beforeEach(async function () {
        driver = await new Builder()
            .usingServer("http://localhost:4444/wd/hub")
            .withCapabilities(capabilities)
            .build();

        vars = {}
    })
    afterEach(async function () {
        await driver.quit();
    })
    it('js-test-robobar', async function () {
        // Test name: js-test-robobar
        // Step # | name | target | value
        // 1 | open | / |
        await driver.get("http://localhost:3000/")
        // 2 | click | css=.ng-scope:nth-child(1) > td .input-group-append > .btn |
        await driver.findElement(By.css(".ng-scope:nth-child(1) > td .input-group-append > .btn")).click()
        // 3 | click | css=.ng-scope:nth-child(2) > td .input-group-append > .btn |
        await driver.findElement(By.css(".ng-scope:nth-child(2) > td .input-group-append > .btn")).click()
        // 4 | click | css=.ng-scope:nth-child(3) .input-group-append > .btn |
        await driver.findElement(By.css(".ng-scope:nth-child(3) .input-group-append > .btn")).click()
        // 5 | click | css=.btn-success |
        await driver.findElement(By.css(".btn-success")).click()
        // 6 | click | id=ageInput |
        await driver.findElement(By.id("ageInput")).click()
        // 7 | type | id=ageInput | 21
        await driver.findElement(By.id("ageInput")).sendKeys("21")
        // 8 | click | css=.btn-success |
        await driver.findElement(By.css(".btn-success")).click()
    })
})
